[package]
name = "url-condenser"
version = "0.1.0"
authors = ["Logan Smith <contact@logansmith.net"]
edition = "2021"
publish = false

[workspace]
members = [".", "api", "storage", "entity", "migration"]

[dependencies]
api = { path = "api" }