version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    user: postgres
    volumes:
      - ./postgres-data/:/postgres-data/db
    environment:
      POSTGRES_DB: url-condenser
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
